<?php
$userhead = 'Password Reset';
$this->headTitle($userhead);
?>

<h1><?= $this->escapeHtml($userhead) ?></h1>
<?php

$email = $resetform->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'Email');
    
$resetform->prepare();

echo $this->form()->openTag($resetform);

?>

<div class="form-group">
    <?= $this->formLabel($email) ?>
    <?= $this->formElement($email) ?>
    <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
</div>

<button class='btn btn-primary' type='submit'>Submit</button>

<?php
    echo $this->form()->closeTag();
?>