<?php
$userhead = 'Enter a new password';
$this->headTitle($userhead);
?>

<h1><?= $this->escapeHtml($userhead) ?></h1>
<?php

$password = $passwordresetform->get('password');
$password->setAttribute('class', 'form-control');
$password->setAttribute('placeholder', 'Password');
    
$passwordresetform->prepare();

echo $this->form()->openTag($passwordresetform);

?>

<div class="form-group">
    <?= $this->formLabel($password) ?>
    <?= $this->formElement($password) ?>
    <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
</div>

<button class='btn btn-primary' type='submit'>Submit</button>

<?php
    echo $this->form()->closeTag();
?>