<?php
    $titlehead = 'My Games';
    $this->headTitle($titlehead);
?>
<h1><?= $this->escapeHtml($titlehead) ?></h1>
<h2>
    <?php 
        if($user)
        {
            echo "Welcome ".$user->firstname;
        }
    ?>
</h2> 
<h3>
    <?php 
        if($user->admin == 0)
        {
            echo "User";
        }
        elseif($user->admin == 1)
        {
            echo "Moderator";
        }
        else
        {
            echo "Head Admin";
        }
    ?>
</h3>
<?php
    if($user->admin == 1 || $user->admin == 2)
    {
    ?>
    <p>
        <a href="<?= $this->url('game', ['action' => 'add']) ?>">Add New Game</a>
    </p>
    <?php 
    }
    ?>

Sorted By: 
<?php 

    foreach ($sortValues as $attribute => $value )
    {
        switch ($value) 
        {
            case "ASC":
                echo ucwords($attribute ." Ascending");
                break;
            case "DESC":
                echo ucwords($attribute. " Descending");
                break;
        }
    } 

?>
<table class="table">
    <tr>
        <th></th>
        <?php
        foreach ($sortValues as $attribute => $value )
        {

        ?>
        <th>
            <a href="<?= $sort == $attribute? '/game?sort=-'.$attribute : '/game?sort=' .$attribute?>"><?=ucwords($attribute)?></a>
            <?php
                switch ($value) 
                {
                    case "ASC":
                        echo "↑";
                        break;
                    case "DESC":
                        echo "↓";
                        break;
                
                }
            ?>
        </th>
        <?php 
        } 
        ?>

        <th></th>
    </tr>

<?php foreach ($games as $game) : ?>
    <tr>
        <td><img src="<?= $game->img ?>" width="160px" height="208px" /></td>
        <td><a href="<?='https://en.wikipedia.org/wiki/'.$game->title?>"> <?=$game->title?></a></td>
        <td><a href="<?='https://en.wikipedia.org/wiki/'.$game->developer?>"> <?=$game->developer?></a></td>
        <td><?= $this->escapeHtml($game->date) ?></td>
        <td><a href="https://pegi.info/what-do-the-labels-mean"> <?=$game->rating?></a></td>
        <td> 
            <?php

                if($game->online == 1)
                {
                    echo "Yes";
                }
                else
                {
                    echo "No";
                }
            ?>
        </td>

        <?php
        if($user->admin == 1 || $user->admin == 2)
        {
        ?>
        <td>
            <a href="<?= $this->url('game', ['action' => 'edit', 'id' => $game->id]) ?>">Edit</a>
            <a href="<?= $this->url('game', ['action' => 'delete', 'id' => $game->id]) ?>">Delete</a>
        </td>
        <?php 
        }
        ?>
    </tr>

<?php endforeach; ?>
</table>