<?php

//ONLY ADMIN HAS PERMISSION TO USE THIS PAGE

$headtitle = 'Edit User';
$this->headTitle($headtitle);
?>
<h1><?= $this->escapeHtml($headtitle) ?></h1>
<?php
$firstname = $form->get('firstname');
$firstname->setAttribute('class', 'form-control');
$firstname->setAttribute('placeholder', 'Firstname');

$surname = $form->get('surname');
$surname->setAttribute('class', 'form-control');
$surname->setAttribute('placeholder', 'Surname');

$dob = $form->get('dob');
$dob->setAttribute('class', 'form-control');
$dob->setAttribute('placeholder', 'Date of Birth');

$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'Email');

$username = $form->get('username');
$username->setAttribute('class', 'form-control');
$username->setAttribute('placeholder', 'Username');

$admin = $form->get('admin');
$admin->setAttribute('class', 'form-control');
//$admin->setAttribute('placeholder', 'Admin');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('users', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($firstname) ?>
    <?= $this->formElement($firstname) ?>
    <?= $this->formElementErrors()->render($firstname, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($surname) ?>
    <?= $this->formElement($surname) ?>
    <?= $this->formElementErrors()->render($surname, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($dob) ?>
    <?= $this->formElement($dob) ?>
    <?= $this->formElementErrors()->render($dob, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($email) ?>
    <?= $this->formElement($email) ?>
    <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($username) ?>
    <?= $this->formElement($username) ?>
    <?= $this->formElementErrors()->render($username, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($admin) ?>
    <?= $this->formElement($admin) ?>
    <?= $this->formElementErrors()->render($admin, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();

?>