<?php
    //ONLY MEMBERS CAN ACCESS THIS PAGE
    $title = 'Registered Users';
    $this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<h2>
    <?php 
        if($user)
        {
            echo "Welcome ".$user->firstname;
        }
    ?>
</h2> 
<br/>

Sorted By: 
<?php
    foreach ($sortValues as $attribute => $value)
    {
        switch($value)
        {
            case "ASC":
                echo ucwords($attribute ." Ascending");
                break;
            case "DESC":
                echo ucwords($attribute. " Descending");
                break;
        }
    }
?>
<table class="table">
    <tr>
        
        <?php
        foreach ($sortValues as $attribute => $value )
        {
        ?>
            <th>
                <a href="<?= $sort == $attribute? '/users?sort=-'.$attribute : '/users?sort=' .$attribute?>"><?=ucwords($attribute)?></a>
                
                <?php
                    switch ($value) 
                    {
                        case "ASC":
                            echo "↑";
                            break;
                        case "DESC":
                            echo "↓";
                            break;
                    }
                ?>
            </th>

        <?php 
        } 
        ?>

            <th>Modify</th>
    </tr>

    <?php
    foreach ($users as $user) : 
    ?>
        <tr>
            <td><?= $this->escapeHtml($user->username) ?></td>
            <td><?= $this->escapeHtml($user->dob) ?></td>
            <td> 
            <?php
                if($user->admin == 1)
                {
                    echo "Yes";
                }
                else
                {
                    echo "No";
                }
            //ONLY ADMINS CAN SEE THIS ?>
            </td>
            <td><?= $this->escapeHtml($user->firstname) ?></td>
            <td><?= $this->escapeHtml($user->surname) ?></td>
            <td><?= $this->escapeHtml($user->email) ?></td>
            <td>
                <a href="<?= $this->url('users', ['action' => 'edit', 'id' => $user->id]) ?>">Edit</a>
                <a href="<?= $this->url('users', ['action' => 'delete', 'id' => $user->id]) ?>">Delete</a>
            </td>
            <? //END ?>
        </tr>

    <?php endforeach; ?>
</table>