<?php

    //ONLY MEMBERS CAN ACCESS THIS PAGE
    $title = 'Registered Users';
    $this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); 
?></h1>

<h2>
    <?php 
        if($user)
        {
            echo "Welcome ".$user->firstname;
        }
    ?>
</h2> 

Sorted By: 
<?php

    foreach ($sortValues as $attribute => $value)
    {
        switch($value)
        {
            case "ASC":
                echo ucwords($attribute ." Ascending");
                break;
            case "DESC":
                echo ucwords($attribute. " Descending");
                break;
        }
    }

?>
<table class="table">
    <tr>
        
        <?php
        foreach ($sortValues as $attribute => $value )
        {
        ?>
            <th>
                <a href="<?= $sort == $attribute? '/users?sort=-'.$attribute : '/users?sort=' .$attribute?>"><?=ucwords($attribute)?></a>
                
                <?php
                    switch ($value) 
                    {
                        case "ASC":
                            echo "↑";
                            break;
                        case "DESC":
                            echo "↓";
                            break;
                    }
                ?>
            </th>

        <?php 
        } 
        ?>

            <th>Modify</th>
    </tr>

    <?php

    foreach ($users as $tableuser) : 
    ?>
        <tr>
            <td><?= $this->escapeHtml($tableuser->username) ?></td>
            <td><?= $this->escapeHtml($tableuser->dob) ?></td>
            <td> 
            <?php
                if($tableuser->admin == 1)
                {
                    echo "Yes";
                }
                else
                {
                    echo "No";
                }
           ?>
            </td>

            <? 
            if($user->admin == 1)
            {
            ?>
                <td><?= $this->escapeHtml($tableuser->firstname) ?></td>
                <td><?= $this->escapeHtml($tableuser->surname) ?></td>
                <td><?= $this->escapeHtml($tableuser->email) ?></td>
                <td>
                    <a href="<?= $this->url('users', ['action' => 'edit', 'id' => $tableuser->id]) ?>">Edit</a>
                    <a href="<?= $this->url('users', ['action' => 'delete', 'id' => $tableuser->id]) ?>">Delete</a>
                </td>
        <? }?>
        </tr>

    <?php endforeach; ?>
</table>